[workspace]
members = [
    "compio",
    "compio-buf",
    "compio-driver",
    "compio-runtime",
    "compio-macros",
    "compio-fs",
    "compio-net",
    "compio-signal",
    "compio-dispatcher",
    "compio-io",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/compio"

[workspace.dependencies]
compio-buf = { path = "./compio-buf", version = "0.1.0" }
compio-driver = { path = "./compio-driver", version = "0.1.0", default-features = false }
compio-runtime = { path = "./compio-runtime", version = "0.1.0" }
compio-macros = { path = "./compio-macros", version = "0.1.0" }
compio-fs = { path = "./compio-fs", version = "0.1.0" }
compio-net = { path = "./compio-net", version = "0.1.0" }
compio-signal = { path = "./compio-signal", version = "0.1.0" }
compio-dispatcher = { path = "./compio-dispatcher", version = "0.1.0" }
