[workspace]
members = [
    "compio",
    "compio-buf",
    "compio-driver",
    "compio-runtime",
    "compio-macros",
    "compio-fs",
    "compio-net",
    "compio-signal",
    "compio-dispatcher",
    "compio-io",
    "compio-tls",
    "compio-log",
    "compio-process",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/compio"

[workspace.dependencies]
compio-buf = { path = "./compio-buf", version = "0.3.0" }
compio-driver = { path = "./compio-driver", version = "0.3.0", default-features = false }
compio-runtime = { path = "./compio-runtime", version = "0.3.0" }
compio-macros = { path = "./compio-macros", version = "0.1.1" }
compio-fs = { path = "./compio-fs", version = "0.3.0" }
compio-io = { path = "./compio-io", version = "0.2.0" }
compio-net = { path = "./compio-net", version = "0.3.0" }
compio-signal = { path = "./compio-signal", version = "0.2.0" }
compio-dispatcher = { path = "./compio-dispatcher", version = "0.2.0" }
compio-log = { path = "./compio-log", version = "0.1.0" }
compio-tls = { path = "./compio-tls", version = "0.2.0", default-features = false }
compio-process = { path = "./compio-process", version = "0.1.0" }

flume = "0.11.0"
cfg-if = "1.0.0"
criterion = "0.5.1"
crossbeam-channel = "0.5.8"
crossbeam-queue = "0.3.8"
futures-channel = "0.3.29"
futures-util = "0.3.29"
libc = "0.2.149"
nix = "0.28.0"
once_cell = "1.18.0"
os_pipe = "1.1.4"
paste = "1.0.14"
slab = "0.4.9"
socket2 = "0.5.6"
tempfile = "3.8.1"
tokio = "1.33.0"
widestring = "1.0.2"
windows-sys = "0.52.0"
