[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:main"

[target.x86_64-unknown-freebsd.env]
passthrough = ["RANLIB_x86_64_unknown_freebsd=x86_64-unknown-freebsd13-ranlib"]

[target.x86_64-unknown-illumos.env]
passthrough = ["RANLIB_x86_64_unknown_illumos=x86_64-unknown-illumos-ranlib"]
