[target.x86_64-unknown-freebsd.env]
passthrough = ["RANLIB_x86_64_unknown_freebsd=x86_64-unknown-freebsd12-ranlib"]

[target.x86_64-unknown-illumos.env]
passthrough = ["RANLIB_x86_64_unknown_illumos=x86_64-unknown-illumos-ranlib"]
